Repository kubeflow/sdk, pull requests merged in 2025-09, with the labels that each got.

#81 chore: Enable parallel builds for coveralls
  .github/workflows/test-python.yaml
Labels: lgtm, approved, size/S

#83 feat(trainer): Refactor get_job_logs() API with Iterator
  README.md
  kubeflow/trainer/api/trainer_client.py
  kubeflow/trainer/backends/base.py
  kubeflow/trainer/backends/kubernetes/backend.py
  kubeflow/trainer/backends/kubernetes/backend_test.py
  kubeflow/trainer/utils/utils.py
Labels: lgtm, approved, size/L

#82 chore: Add welcome new contributors CI
  .github/workflows/welcome-new-contributors.yaml
Labels: lgtm, approved, size/M

#65 feat(ci): Add automated release CI job
  .github/workflows/release.yml
  Makefile
  RELEASE.md
  pyproject.toml
  scripts/gen-changelog.py
  uv.lock
Labels: lgtm, approved, size/XL

#101 chore: Ignore PRs titles with area/release labels in CI
  .github/workflows/check-pr-title.yaml
Labels: lgtm, approved, size/XS

#100 Kubeflow SDK Official Release 0.1.0rc1
  kubeflow/__init__.py
Labels: lgtm, approved, size/XS, area/release
