Repository kubeflow/sdk, pull requests merged in 2025-08, with the labels that each got.

#54 feat(trainer): Add environment variables argument to CustomTrainer
  python/kubeflow/trainer/api/trainer_client_test.py
  python/kubeflow/trainer/types/types.py
  python/kubeflow/trainer/utils/utils.py
Labels: lgtm, approved, size/M

#56 feat(trainer): Support Framework Labels in Runtimes
  python/kubeflow/trainer/__init__.py
  python/kubeflow/trainer/api/trainer_client.py
  python/kubeflow/trainer/api/trainer_client_test.py
  python/kubeflow/trainer/constants/constants.py
  python/kubeflow/trainer/types/types.py
  python/kubeflow/trainer/utils/utils.py
Labels: lgtm, approved, size/XL

#55 chore(ci): Add dev tests with master dependencies
  .flake8
  .github/workflows/check-pr-title.yaml
  .github/workflows/github-stale.yaml
  .github/workflows/test-e2e.yaml
  .github/workflows/test-python.yaml
  CONTRIBUTING.md
  Makefile
  python/kubeflow/trainer/api/__init__.py
  python/pyproject.toml
  python/uv.lock
Labels: lgtm, approved, size/L

#61 chore: move pyproject.toml to root
  .github/workflows/test-e2e.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  kubeflow/__init__.py
  kubeflow/py.typed
  kubeflow/trainer/__init__.py
  kubeflow/trainer/api/__init__.py
  kubeflow/trainer/api/trainer_client.py
  kubeflow/trainer/api/trainer_client_test.py
  kubeflow/trainer/constants/__init__.py
  kubeflow/trainer/constants/constants.py
  kubeflow/trainer/types/__init__.py
  kubeflow/trainer/types/types.py
  kubeflow/trainer/utils/__init__.py
  kubeflow/trainer/utils/utils.py
  pyproject.toml
  python/kubeflow/trainer/types/__init__.py
  uv.lock
Labels: lgtm, approved, size/M

#64 fix(trainer): Keep the original runtime command in get_runtime_packages() API
  kubeflow/trainer/api/trainer_client.py
Labels: lgtm, approved, size/S

#68 feat: Implement Kubernetes Backend
  Makefile
  kubeflow/trainer/api/trainer_client.py
  kubeflow/trainer/backends/__init__.py
  kubeflow/trainer/backends/base.py
  kubeflow/trainer/backends/kubernetes/__init__.py
  kubeflow/trainer/backends/kubernetes/backend.py
  kubeflow/trainer/backends/kubernetes/backend_test.py
  kubeflow/trainer/backends/kubernetes/types.py
  kubeflow/trainer/types/types.py
  kubeflow/trainer/utils/utils.py
Labels: size/XXL, lgtm, approved

#78 fix: trainer client backend public
  kubeflow/trainer/api/trainer_client.py
Labels: lgtm, approved, size/S
