Repository kubeflow/sdk, pull requests merged in 2025-07, with the labels that each got.

#28 fix: Expose BuiltinTrainer API to users
  python/kubeflow/trainer/api/trainer_client.py
  python/kubeflow/trainer/constants/constants.py
  python/kubeflow/trainer/types/types.py
  python/kubeflow/trainer/utils/utils.py
Labels: lgtm, approved, size/M

#37 Step down from sdk ownership role
  OWNERS
Labels: lgtm, approved, size/XS

#38 Add support for UV & Ruff
  .github/workflows/test-python.yaml
  .gitignore
  .pre-commit-config.yaml
  Makefile
  python/kubeflow/trainer/utils/utils.py
  python/pyproject.toml
  python/uv.lock
Labels: lgtm, approved, size/XL

#17 add unit test for trainer sdk
  .github/workflows/test-python.yaml
  .gitignore
  Makefile
  python/kubeflow/trainer/api/trainer_client_test.py
  python/kubeflow/trainer/utils/utils.py
  python/pyproject.toml
  python/uv.lock
Labels: size/XXL, lgtm, approved, ok-to-test

#42 feat(ci): Add GitHub action to verify PR titles
  .github/workflows/check-pr-title.yaml
Labels: lgtm, approved, size/M

#43 fix(trainer): fix __all__ import.
  python/kubeflow/trainer/__init__.py
Labels: lgtm, approved, size/XS

#51 chore(trainer): Remove accelerator label from the runtimes
  python/kubeflow/trainer/api/trainer_client_test.py
  python/kubeflow/trainer/constants/constants.py
  python/kubeflow/trainer/types/types.py
  python/kubeflow/trainer/utils/utils.py
Labels: lgtm, approved, size/S

#52 feat(trainer): Add `wait_for_job_status()` API
  python/kubeflow/trainer/__init__.py
  python/kubeflow/trainer/api/trainer_client.py
  python/kubeflow/trainer/api/trainer_client_test.py
  python/kubeflow/trainer/constants/constants.py
  python/kubeflow/trainer/types/types.py
  python/kubeflow/trainer/utils/utils.py
Labels: lgtm, approved, size/XL
